### ISSUE TITLE
Problem: wrong data on call to action

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/website#1]
Problem:
<img width="951" alt="screen shot 2018-07-13 at 15 00 25" src="https://user-images.githubusercontent.com/8143945/42677408-37daa4fc-86ae-11e8-8334-531b53406796.png">

These should be:
Who we are
What we do
How we can help

Appropriate icons from font-awesome should be used.

"We provide awesome....." should be "Supporting the **Cardano** ecosystem"

**Comment by AshHimself** [comment]
claim

**Comment by AshHimself** [comment]
Done in #9
