### ISSUE TITLE
problem: site colour not defined

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/website#11]
solution: choose a theme colour from the available colours or a new colour, then remove the theme selector element

![image](https://user-images.githubusercontent.com/148682/42793263-e28e1500-89ab-11e8-8912-0730e4165bbb.png)

@gazhayes

**Comment by gazhayes** [comment]
I guess yellow

**Comment by AshHimself** [comment]
claim.. yellow it is!!

**Comment by AshHimself** [comment]
Fixed in #14
