### ISSUE TITLE
Problem: [Common] Template styles are not selected as per set it

### ISSUE THREAD

**Issue by akatrodiya** [EmurgoHK/website#12]
Problem: When Template styles are set it affect it to site and options which are select to change style are show as selected options, but when we reopen site, site is looks perfect as per selected options, and when we show in 'Template styles' menu it showing default options as selected options

![bug](https://user-images.githubusercontent.com/15026463/42797134-58b3e314-89ab-11e8-8bd7-6e4b4e5864c5.png)

Solution: Display Template styles options as selected options which is apply in current view

**Comment by gazhayes** [comment]
These style options will be removed

**Comment by AshHimself** [comment]
This can be closed as the theme switcher is removed in #14
