### ISSUE TITLE
Problem: social links are not set

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/website#15]
solution: set social links to valid url's 

![image](https://user-images.githubusercontent.com/148682/42816869-cb72ace8-89fe-11e8-833f-1ce0fe8ee00b.png)

**Comment by naomazik** [comment]
Please remove : skype, Flickr, pintrest, and googleplus
Add Telegram super group, Medium, youtube and Meetup

The social pages
FB : https://www.facebook.com/EmurgoHK/
LinkedIn : https://www.linkedin.com/company/emurgohk/
Twitter : https://twitter.com/EmurgoHK
Meduim: https://medium.com/emurgohk

**Comment by anbud** [comment]
Claim.

**Comment by anbud** [comment]
Done in #21.
