### ISSUE TITLE
problem: no emugroHK logo is used

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/website#16]
solution: add logo to site and where required

@gazhayes do you have a PSD or PNG?

**Comment by gazhayes** [comment]
Ah yeah, I'll get that off someone at this end tomorrow

**Comment by AshHimself** [comment]
What about any other branding? I'm not digging these images on the home page and thinking something a little more flat like the https://emurgo.io website would be more professional.

**Comment by gazhayes** [comment]
Here's a logo in AI format: https://drive.google.com/file/d/1lftYHaN85eK03fTCyZtsXEhUiUPZyB0Y/view

**Comment by gazhayes** [comment]
> I'm not digging these images on the home page and thinking something a little more flat

I'm trying to present it more as a community organisation rather than a corporate type thing (because it's mostly an accelerator/incubator.

**Comment by AshHimself** [comment]
oh in that case the walrus should come back out... jokes.. 

claim

**Comment by gazhayes** [comment]
I might write a script to slip it in once every thousand visits just for fun

**Comment by AshHimself** [comment]
@gazhayes - This is all done now, took a bit to do as I had to get software that could edit AI files and then change the font color to make it look better on the website. Thinking the logo could look better a bit bigger?
