### ISSUE TITLE
problem: search does not function

### ISSUE THREAD

**Issue by AshHimself** [EmurgoHK/website#18]
solution: investigate if this is required if so decide on backend technology to search the site.

@gazhayes 

![image](https://user-images.githubusercontent.com/148682/42817110-a62dd9d4-89ff-11e8-8dd0-fb1d7920df71.png)

**Comment by gazhayes** [comment]
Just nuke it, this is always going to be hosted on github and updated with the C4 (currently visible at https://emurgohk.github.io/website/ but will later be moved to emurgohk.io).

**Comment by anbud** [comment]
Claim.

**Comment by anbud** [comment]
Done in #23.
