### ISSUE TITLE
problem: stock text on second call to action

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/website#2]
problem:
<img width="958" alt="screen shot 2018-07-13 at 15 11 37" src="https://user-images.githubusercontent.com/8143945/42677739-46636fd0-86af-11e8-8e13-59a75d1019a6.png">

solution:
change icon to a rocket from font awesome

"Solana is a Responsive Multipurpose Theme" => "Emurgo provides funding and acceleration"

"Purchase it" => "APPLY NOW"

"Easy Customizable, Retina Ready, Cross-Browser Compatible, Unlimited Colors" => 
"Want to build something on Cardano? We're here to help!"

**Comment by AshHimself** [comment]
Claim
