### ISSUE TITLE
Problem : We do not send newsletters

### ISSUE THREAD

**Issue by naomazik** [EmurgoHK/website#20]
<img width="1275" alt="screen shot 2018-07-18 at 12 02 04 am" src="https://user-images.githubusercontent.com/39718454/42830480-23f4722e-8a1e-11e8-9e8b-fa38f16c98da.png">
 Solution : Remove this Newsletter signing up form

**Comment by anbud** [comment]
Claim.

**Comment by anbud** [comment]
Done in #22.
