### ISSUE TITLE
problem: no slider images

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/website#6]
problem: no slider images

solution: choose some images from here to use in the slider, whoever does this one can choose whatever they think looks good:
https://photos.google.com/share/AF1QipPmtCWBxs0JraLDAl89kItkvIcPvRITvENA6qqt36hU5gD9gHCQ6RHQsBj-f-Nm4g?key=bmdzWVFxdDhkU0FVXzlqa1dBbm1uN3JaeExGeHRn

**Comment by AshHimself** [comment]
claim

**Comment by AshHimself** [comment]
@gazhayes - Is the purpose of this site to more sell the product or a service? I only ask because those pictures are more of people. I got it up and running locally now and added one in same dimensions as the sample slider backgrounds. 

![image](https://user-images.githubusercontent.com/148682/42759980-60fffe56-893b-11e8-8661-69dd82f9b942.png)

**Comment by samuelralak** [comment]
lol, that’s Charles Hoskinson :D, looks like Charles Hoskinson

**Comment by AshHimself** [comment]
haha I duno.. @gazhayes said choose some images...

**Comment by samuelralak** [comment]
@AshHimself  from what I understand about Emurgo and EmurgoHK, the purpose of the website is to more sell a service. They provide financial backing (not limited to this I suppose) to startups looking to develop on the Cardano Blockchain.

**Comment by gazhayes** [comment]
> lol, that’s Charles Hoskinson :D, looks like Charles Hoskinson

So is this, with yours truly in the background ;)
![photo6226754534345123945](https://user-images.githubusercontent.com/8143945/42766638-8882c29e-894d-11e8-85bf-428cd91f8d3c.jpg)

> Is the purpose of this site to more sell the product or a service

We are basically the incubator/accelerator arm of Emurgo (emurgo.io) so you can use emurgo.io as a reference (very loosely). We aren't actually selling anything but investing seed capital and providing support for young teams who want to build stuff on the cardano blockchain.

**Comment by AshHimself** [comment]
hahaha... ok well i'll choose three photos then including the one above.

**Comment by AshHimself** [comment]
haha I won't.

pushed in #8 If you have any other images it may help make it look a little more relevant but this will do for now to get rid of the default ones.
