### ISSUE TITLE
problem: not sure who wants to work on this site

### ISSUE THREAD

**Issue by gazhayes** [EmurgoHK/website#7]
solution:

ping @geekyd @chamidu-supeshala @samuelralak @anbud @AshHimself @akatrodiya anyone who's interested start watching this repo.

**Comment by AshHimself** [comment]
@gazhayes cloned and ready to roll.

**Comment by gazhayes** [comment]
I haven't got emurgobot onto this repo yet but just claim as usual and I'll get it working today sometime.

**Comment by anbud** [comment]
I'm not sure how helpful I'll be as this is mostly frontend I guess, but I'm in. :)
